services:
  mongodb:
    image: mongo:8.0.1
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: dev
  wishlist:
    build: .
    container_name: wishlist
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      HOST: mongodb
